export const finnhubKey = process.env.REACT_APP_FINNHUB_KEY;
export const finnhubBase = 'https://finnhub.io/api/v1/';
export const GRAPHQL_API = "http://localhost:4000/graphql";
export const VIRUS_API = "https://covidtracking.com/api/us/daily";
export const tickers = [
    { ticker: 'JPM', name: 'JPMorgan Chase & Co' },
    { ticker: 'BRK.A', name: 'Bank of America Corp' },
    { ticker: 'BAC', name: 'Berkshire Hathaway Inc' },
    { ticker: 'AAPL', name: 'Apple Inc' },
    { ticker: 'T', name: 'AT&T Inc' },
    { ticker: 'GOOGL', name: 'Alphabet Inc' },
    { ticker: 'MSFT', name: 'Microsoft Corp' },
    { ticker: 'XOM', name: 'Wells Fargo & Co' },
    { ticker: 'WFC', name: 'Exxon Mobil Corp' },
    { ticker: 'C', name: 'Citigroup Inc' },
    { ticker: 'WMT', name: 'Walmart Inc' },
    { ticker: 'VZ', name: 'Verizon Communications Inc' },
    { ticker: 'AMZN', name: 'Amazon.com Inc' },
    { ticker: 'UNH', name: 'UnitedHealth Group Inc' },
    { ticker: 'CMCSA', name: 'Comcast Corp' },
    { ticker: 'JNJ', name: 'Johnson & Johnson' },
    { ticker: 'DIS', name: 'Walt Disney Co' },
    { ticker: 'INTC', name: 'Intel Corp' },
    { ticker: 'FB', name: 'Facebook Inc' },
    { ticker: 'CVS', name: 'CVS Health Corp' },
    { ticker: 'GS', name: 'Goldman Sachs Group Inc' },
    { ticker: 'MS', name: 'Morgan Stanley' },
    { ticker: 'PFE', name: 'Pfizer Inc' },
    { ticker: 'IBM', name: 'International Business Machines Corp' },
    { ticker: 'GE', name: 'General Electric Co' },
    { ticker: 'CVX', name: 'Chevron Corp' },
    { ticker: 'CI', name: 'Cigna Corp' },
    { ticker: 'PG', name: 'Procter & Gamble Co' },
    { ticker: 'MET', name: 'MetLife Inc' },
    { ticker: 'CSCO', name: 'Cisco Systems Inc' },
    { ticker: 'RTX', name: '' },
    { ticker: 'PEP', name: 'PepsiCo Inc' },
    { ticker: 'AXP', name: 'American Express Co' },
    { ticker: 'GM', name: 'General Motors Co' },
    { ticker: 'MRK', name: 'Merck & Co Inc' },
    { ticker: 'ORCL', name: 'Oracle Corp' },
    { ticker: 'KO', name: 'Coca-Cola Co' },
    { ticker: 'USB', name: 'U.S. Bancorp' },
    { ticker: 'ANTM', name: 'Anthem Inc' },
    { ticker: 'HD', name: 'Home Depot Inc' },
    { ticker: 'PRU', name: 'Prudential Financial Inc' },
    { ticker: 'ABBV', name: 'Abbvie Inc' },
    { ticker: 'DELL', name: 'Dell Technologies Inc' },
    { ticker: 'CAT', name: 'Caterpillar Inc' },
    { ticker: 'WBA', name: 'Walgreens Boots Alliance Inc' },
    { ticker: 'BMY', name: 'Bristol-Myers Squibb Co' },
    { ticker: 'PNC', name: 'PNC Financial Services Group Inc' },
    { ticker: 'V', name: 'Visa Inc' },
    { ticker: 'COST', name: 'Costco Wholesale Corp' },
    { ticker: 'UPS', name: 'United Parcel Service Inc' },
    { ticker: 'DUK', name: 'Duke Energy Corp' },
    { ticker: 'LMT', name: 'Lockheed Martin Corp' },
    { ticker: 'CHTR', name: 'Charter Communications Inc' },
    { ticker: 'HON', name: 'Honeywell International Inc' },
    { ticker: 'AIG', name: 'American International Group Inc' },
    { ticker: 'ABT', name: 'Abbott Laboratories' },
    { ticker: 'BK', name: 'Bank of New York Mellon Corp' },
    { ticker: 'COF', name: 'Capital One Financial Corp' },
    { ticker: 'AMGN', name: 'Amgen Inc' },
    { ticker: 'TFC', name: 'Truist Financial Corp' },
    { ticker: 'EXC', name: 'Exelon Corp' },
    { ticker: 'LOW', name: "Lowe's Companies Inc" },
    { ticker: 'SO', name: 'Southern Co' },
    { ticker: 'BLK', name: 'BlackRock Inc' },
    { ticker: 'NEE', name: 'Nextera Energy Inc' },
    { ticker: 'DE', name: 'Deere & Co' },
    { ticker: 'UNP', name: 'Union Pacific Corp' },
    { ticker: 'TMO', name: 'Thermo Fisher Scientific Inc' },
    { ticker: 'GILD', name: 'Gilead Sciences Inc' },
    { ticker: 'PSX', name: 'Phillips 66' },
    { ticker: 'MDLZ', name: 'Mondelez International Inc' },
    { ticker: 'AVGO', name: 'Broadcom Inc' },
    { ticker: 'MMM', name: '3M Co' },
    { ticker: 'TGT', name: 'Target Corp' },
    { ticker: 'MPC', name: 'Marathon Petroleum Corp' },
    { ticker: 'PGR', name: 'Progressive Corp' },
    { ticker: 'COP', name: 'ConocoPhillips' },
    { ticker: 'PM', name: 'Philip Morris International Inc' },
    { ticker: 'MCD', name: "Mcdonald's Corp" },
    { ticker: 'GD', name: 'General Dynamics Corp' },
    { ticker: 'AFL', name: 'Aflac Inc' },
    { ticker: 'TRV', name: 'Travelers Companies Inc' },
    { ticker: 'LLY', name: 'Eli Lilly and Co' },
    { ticker: 'KHC', name: 'Kraft Heinz Co' },
    { ticker: 'SCHW', name: 'Charles Schwab Corp' },
    { ticker: 'HCA', name: 'HCA Healthcare Inc' },
    { ticker: 'DHR', name: 'Danaher Corp' },
    { ticker: 'HUM', name: 'Humana Inc' },
    { ticker: 'NOC', name: 'Northrop Grumman Corp' },
    { ticker: 'NKE', name: 'Nike Inc' },
    { ticker: 'PYPL', name: 'PayPal Holdings Inc' },
    { ticker: 'QCOM', name: 'Qualcomm Inc' },
    { ticker: 'DAL', name: 'Delta Air Lines Inc' },
    { ticker: 'KR', name: 'Kroger Co' },
    { ticker: 'MA', name: 'Mastercard Inc' },
    { ticker: 'D', name: 'Dominion Energy Inc' },
    { ticker: 'MU', name: 'Micron Technology Inc' },
    { ticker: 'NFLX', name: 'Netflix Inc' },
    { ticker: 'HPQ', name: 'HP Inc' },
    { ticker: 'SBUX', name: 'Starbucks Corp' }
]

export const significantDates = {
     "12/31/19": "Chinese authorities treated dozens of cases of pneumonia of unknown cause.", 
     "1/11/20": "China reported its first death.",
     "1/21/20": "First confirmed case in Washington state.", 
     "1/23/20": "Wuhan, a city of more than 11 million, was cut off by the Chinese authorities.",
     "1/30/20": "The W.H.O. declared a global health emergency.",
     "2/2/20": "The first coronavirus death was reported outside China.",
     "2/5/20": "A cruise ship in Japan quarantined thousands.",
     "2/7/20": "A Chinese doctor who tried to raise the alarm died.",
     "2/11/20": "The disease the virus causes was named.",
     "2/14/20": "France announced the first coronavirus death in Europe.",
     "2/19/20": "Hundreds left the quarantined cruise.",
     "2/21/20": "A secretive church was linked to the outbreak in South Korea.",
     "2/23/20": "Italy saw a major surge in cases.",
     "2/24/20": "Iran emerged as a second focus point.",
     "2/26/20": "Latin America reported its first case.",
    "2/28/20": ["Infections spiked in Europe.","Sub-Saharan Africa recorded its first infection."],
    "2/29/20": "The United States reported a death.",
    "3/3/20": "U.S. officials approved widespread testing.",
    "3/11/20": "President Trump blocked most visitors from continental Europe.",
    "3/13/20": "President Trump declared a national emergency.",
    "3/15/20": "The C.D.C. recommended no gatherings of 50 or more people in the U.S.",
    "3/16/20": "Latin America began to feel the effects.",
    "3/17/20": ["France imposed a nationwide lockdown.","The E.U. barred most travelers from outside the bloc."],
    "3/19/20": "For the first time, China reported zero local infections.",
    "3/23/20": "Prime Minister Boris Johnson locked Britain down.",
    "3/24/20": ["The Tokyo Olympics were delayed until 2021."," India announced a 21-day lockdown."],
    "3/26/20": "The United States led the world in confirmed cases.",
    "3/27/20": "Trump signed a stimulus bill into law.",
    "3/28/20": "The C.D.C. issued a travel advisory for the New York region.",
    "3/30/20": "More states issued stay-at-home directives.",
    "4/2/20": "Cases topped one million, and millions lost their jobs.",
    "4/6/20": "Prime Minister Boris Johnson moved into intensive care.",
    "4/8/20": "Companies planned vaccine trials.",
    "4/10/20": "Cases surged in Russia.",
    "4/14/20": ["President Trump planned to stop U.S. funding of the W.H.O.","The global economy slid toward contraction."],
    "4/17/20": "President Trump encouraged protests against some state restrictions.",
    "4/19/20": "Chile issued ‘immunity cards’ to people who have recovered from the virus.",
    "4/21/20": "Officials discovered earlier known U.S. coronavirus deaths in California.",
    "4/24/20": ["The European Union, pressured by China, watered down a report on disinformation.","The president was criticized over disinfectant comments."],
    "4/26/20": "The global death toll surpassed 200,000.",
    "4/27/20": "Oxford scientists led the race for a vaccine.",
    "4/30/20": "Airlines announced rules requiring face masks.",
    "5/1/20": ["The F.D.A. authorized emergency use of an antiviral drug.","The W.H.O. extended its declaration of a global public health emergency."],
    "5/3/20": "Several countries targeted China over the coronavirus.",
    "5/5/20": "The coronavirus reached France in December, doctors said, rewriting the epidemic’s ",
    "5/6/20": "Poland delayed its presidential election.",
    "5/10/20": "The British prime minister relaxed certain restrictions.",
    "5/13/20": "A top W.H.O. official said the coronavirus ‘may never go away.’",
    "5/16/20": "Barack Obama criticized the U.S.’s virus response.",
    "5/17/20": "Japan and Germany, two of the world’s largest economies, enter recessions.",
}
